---
- name: To install nop commerece application
  hosts: all
  become: yes
  tasks:
    - name: installing and update the apache2 server
      apt:
        name: apache2
        upadate_cache: yes
        state: present
    - name: wget the dpkg packages
      get_url: 
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: packages-microsoft-prod.deb

    - name: Installing "packages-microsoft-prod.deb" by using the dpkg
      dpkg_selections:
        name: packages-microsoft-prod.deb
        selection: install

    - name: update and install the .net application
      apt:
        name: apt-transport-https aspnetcore-runtime-6.0
        update_cache: yes
        state: yes
    - name: Create the dirctory /var/www/nopCommerce450 
      ansible.builtin.file:
        path: /var/www/nopCommerce450
        state: directory
    - name: To install the unzip
      apt:
        name: unzip
        update_cache: yes
        state: present    
    - name : unzip the nop commerece
      ansible.builtin.unarchive:
        src:  https://github.com/nopSolutions/nopCommerce/releases/download/release-4.50.2/nopCommerce_4.50.2_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce450
    - name: make dircotry as bin
      file:
        path: /var/www/bin
        state: directory
    - name: make dircotry as logs
      file: 
        path: /var/www/logs
        state: directory     
    - name: Create the /etc/systemd/system/nopCommerce450.service 
      file:
        src: nopCommerce450.service
        dest: /etc/systemd/system/nopCommerce450.service
    - name: Nopcommerce450 service start and status
      ansible.builtin.systemd:
        name: nopCommerce450.service
        state: start      




          
  


