---
- name: To install Nop commerece on ubuntu
  hosts: all
  become: yes
  tasks: 
    - name: To download the microsoft dpkg packages
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /home/devops/packages-microsoft-prod.deb

    - name: To run the dpkg -i command by using the shell
      ansible.builtin.shell: dpkg -i packages-microsoft-prod.deb  

    - name: To install & update the .net application 
      apt:
        name: apt-transport-https 
        state: present 

    - name: To install .net application
      apt:
        name: dotnet-sdk-2.2
        state: present  
        update_cache: yes  

    - name: To run the a
      ansible.builtin.shell: dotnet --list-runtimes

    - name: To install the mysql server
      apt:
        name: mysql-server
        state: present

    - name: To run and set user and password for mysql we use the shell
      ansible.builtin.shell: /usr/bin/mysql_secure_installation

    - name: To install the nginx
      apt:
        name: nginx
        state: present

    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        state: started
        name: nginx   

    - name: To know the status we use the shell
      ansible.builtin.shell: systemctl status nginx 

    - name: To  edit the default /etc/nginx/sites-available/default 
      file:
        src: default
        dest: /etc/nginx/sites-available/default 

    - name: To Create dirctroy /var/www/nopCommerce450
      ansible.builtin.file:
        path: /var/www/nopCommerce450
        state: directory

    - name: To install the uzip
      apt:
        name: unzip
        update_cache: yes
        state: present

    - name: To get the nop commerece application from link and unzip will happen
      ansible.builtin.unarchive:
        src:  https://github.com/nopSolutions/nopCommerce/releases/download/release-4.50.2/nopCommerce_4.50.2_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce450

    - name: make dircotry as bin
      file:
        path: /var/www/bin
        state: directory

    - name: make dircotry as logs
      file: 
        path: /var/www/logs
        state: directory     

    - name: Create the /etc/systemd/system/nopCommerce450.service 
      file:
        src: nopCommerce450.service
        dest: /etc/systemd/system/nopCommerce450.service

    - name: Nopcommerce450 service start and status
      ansible.builtin.systemd:
        name: nopCommerce450.service
        state: start                 
            
    