---

- name: Configuring apache2
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  notify: test and reload apache2
  with_items:
    - etc/apache2/apache2.conf
    - etc/apache2/ports.conf
    - etc/apache2/conf-available/security.conf
