---

- name: Creating webroots
  file:
    dest: "{{ apache2_sites_basedir }}/{{ item.id }}/htdocs"
    mode: "0755"
    state: directory
  when: item.add_webroot is defined and item.add_webroot
  with_items: "{{ apache2_sites }}"

- name: Creating sites
  template:
    src: "{{ item.template|default(apache2_sites_template) }}"
    dest: "/etc/apache2/sites-available/{{ item.id }}.conf"
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ apache2_sites }}"
  notify: test and reload apache2

- name: Enabling sites
  file:
    src: "/etc/apache2/sites-available/{{ item.id }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ item.id }}.conf"
    state: link
  when: item.state is not defined or item.state == 'present'
  with_items: "{{ apache2_sites }}"
  notify: test and reload apache2

- name: Disabling sites
  file:
    src: "/etc/apache2/sites-enabled/{{ item.id }}.conf"
    state: absent
  when: item.state is defined and item.state == 'absent'
  with_items: "{{ apache2_sites }}"
  notify: test and reload apache2
