---
- name: To install the odoo from source code 
  hosts: all 
  become: yes
  tasks:
    - name: To get source code from the git repo 
      ansible.builtin.git:
        repo: "{{ git_url }}"
        dest: "{{ git_dest }}"
    - name: To install the pip3 python3 postgresql and postgresql-client
      apt:
        name: "{{ item }}"
        state: present 
        update_cache: yes
      with_items:
         - python3
         - python3-pip  
         - postgresql
         - postgresql-client
    - name: To create the postgres user
      builtin.command: sudo -u postgres createuser -s $USER; createdb $USER
      ignore_errors: True
    - name: To install the all package
      apt:
        name: "{{ item }}"  
        update_cache: yes
      with_items:
        - python3-dev
        - libxml2-dev
        - libxslt1-dev
        - libldap2-dev
        - libsasl2-dev
        - libtiff5-dev
        - libjpeg8-dev
        - libopenjp2-7-dev
        - zlib1g-dev
        - libfreetype6-dev
        - liblcms2-dev
        - libwebp-dev
        - libharfbuzz-dev
        - libfribidi-dev
        - libxcb1-dev
        - libpq-dev
      state: present 
    - name: To install the pip3 setuptools and requirements.txt  
      pip:
        name: "{{ item }}"
        state: present 
      with_items:
        - setuptools 
        - wheel   
    - name: To run the requirements.txt by using pip module
      pip:
        requirements: "{{ git_dest }}/requirements.txt"
        
    - name: To install the node js and  npm
      apt:
        name: "{{ item }}"    
        state: present 
      with_items:
        - nodejs
        - npm 
    - name: To install the rtlcss 
      npm:
        name: rtlcss
        state: present 
        global: yes      

    - name: To run the application by using command
      builtin.shell: python3 odoo-bin --addons-path=addons -d mydb &
      async: '*'
      poll: 0


  
    






















    

 