---
- name: To install Nop commerece on ubuntu
  hosts: all
  become: yes
  tasks: 
    - name: To download the microsoft dpkg packages
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /home/devops//packages-microsoft-prod.deb

    - name: install the debian package
      apt:
        deb: /home/devops/packages-microsoft-prod.deb  

    - name: To install & update the .net application and uzip
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      with_items:
       - apt-transport-https
       - aspnetcore-runtime-3.1 
       - unzip 
       - mysql-server
       - apache2

    - name: To run the a
      ansible.builtin.shell: dotnet --list-runtimes
   
   # - name: To check the apache2 server systemctl
    #  ansible.builtin.shell: systemctl status apache2


    - name: To Create dirctroy /var/www/nopCommerce450
      file:
        path: /var/www/nopCommerce450
        owner: www-data
        group: www-data
        state: directory
    #- name: To get the nop commerece application.
     # ansible.builtin.get_url:
      #  url:  https://github.com/nopSolutions/nopCommerce/releases/download/release-4.50.2/nopCommerce_4.50.2_NoSource_linux_x64.zip
      #  dest: /var/www/nopCommerce450

    - name: To get the nop
      ansible.builtin.unarchive:
        src: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.50.2/nopCommerce_4.50.2_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce450
        remote_src: yes    

 #   - name: To unzip the nop commerce
  #    unarchive:
   #     src: /var/www/nopCommerce450
    #    dest: /var/www/nopCommerce450
     #   remote_src: yes   

    - name: make dircotry as bin
      file:
        path: /var/www/bin
        owner: www-data
        group: www-data
        state: directory 

    - name: make dircotry as logs
      file:
        path: /var/www/logs 
        owner: www-data
        group: www-data 
        state: directory

    - name: To run the .net application via shell command using &
      ansible.builtin.shell: /usr/bin/dotnet /var/www/nopCommerce450/Nop.Web.dll &

    - name: To enbale the reverse proxy
      community.general.apache2_module:
        name: "{{ item }}"
        state: present
      with_items:
        - a2enmod proxy
        - a2enmod proxy_http
    - name: To create the file /etc/apache2/sites-available
      ansible.builtin.template:
        src: /nop.conf
        dest: /etc/apache2/sites-available/nop.conf
    - name: enable the a2ensite nop.conf
      ansible.builtin.shell: a2ensite nop.cnf
    - name: Make sure apache2
      ansible.builtin.systemd:
        state: restarted
        name: apache2
        daemon_reload: yes    


  

  
        
        

   
            
    